Practical_6: Numpy

Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [2]:
import numpy as np

In [12]:
my_int=np.arange(1,11)
my_int

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [64]:
my_array = np.zeros((3,3))
my_array.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [14]:
my_evenly = np.linspace(0, 5, 10)
print(my_evenly)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [24]:
my_five = np.array([[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0],[0,0,0,1,0], [0,0,0,0,1]])
my_five

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [19]:
matrix = np.random.rand(4, 4)  
matrix

array([[0.93711163, 0.15623631, 0.84303857, 0.15524518],
       [0.77326055, 0.01054402, 0.64864639, 0.37636548],
       [0.40858546, 0.31339509, 0.18992873, 0.56441552],
       [0.49713107, 0.39625419, 0.08598607, 0.36775246]])

Exercise 6:
Find the shape of a NumPy array.

In [20]:
print("matrix shape:", matrix.shape)

matrix shape: (4, 4)


Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [35]:
array_1d = np.arange(16)  
matrix_4 = array_1d.reshape(4, 4)  
my_A=array_1d
my_A
matrix_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
np.random.seed(10)
A=np.random.rand(4,4)
A

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [30]:
np.random.seed(10)
A=np.random.rand(4,4)
A


array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

Exercise 8:
Find the data type of the elements in a NumPy array.

In [36]:
A.dtype

dtype('float64')

Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [44]:
A=np.arange(2,101,2)
A

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [48]:
A=np.random.randint(10,50,(6,6))
A

array([[22, 15, 49, 18, 47, 47],
       [19, 46, 16, 31, 11, 16],
       [12, 43, 46, 39, 34, 28],
       [46, 12, 19, 45, 27, 46],
       [38, 29, 12, 10, 41, 13],
       [20, 45, 17, 18, 38, 47]])

Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [56]:
import numpy as np  
A = np.array([[1, 2, 3, 4],  
              [5, 6, 7, 8],  
              [9, 10, 11, 12],  
              [13, 14, 15, 16]])   
submatrix = A[1:3, 1:3] 
print(A)  

print("\nExtracted Submatrix:")  
print(submatrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Extracted Submatrix:
[[ 6  7]
 [10 11]]


Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [57]:
A=np.array([1,2,3,4,5])
np.sum(A)

15

Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [58]:
A=np.array([1,2,3,4,5])
np.mean(A)

3.0

In [64]:
A=np.array([5,3,1,4,2])
B=np.sort(A)
C=len(B)
if(C%2==0):
    print("Median is ", C/2)
else:
    print("Median is ",(C+1)/2)

Median is  3.0


In [69]:
A=np.array([5,3,1,4,2])
np.std(A,ddof=0)

1.4142135623730951

In [66]:
help(np.std)

Help on _ArrayFunctionDispatcher in module numpy:

std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
    Compute the standard deviation along the specified axis.

    Returns the standard deviation, a measure of the spread of a distribution,
    of the array elements. The standard deviation is computed for the
    flattened array by default, otherwise over the specified axis.

    Parameters
    ----------
    a : array_like
        Calculate the standard deviation of these values.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the standard deviation is computed. The
        default is to compute the standard deviation of the flattened array.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a standard deviation is performed over
        multiple axes, instead of a single axis or all the axes as before.
    dtype : dtype, optional
        Type to use in computing the standard deviation. For 

Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [71]:
A=np.array([5,3,1,4,2])
print("The maximum is : ",np.max(A))
print("The minimum is : ",np.min(A))

The maximum is :  5
The minimum is :  1


Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [22]:
A = np.random.randint(0, 100, size=20)  
print(A)
maxvalue=np.argmax(A)
print(maxvalue)

[99 82 14 75 54 51 16 15 19 32 17 76 53  7  9 23 14 11 92 62]
0


Exercise 16:
Create a NumPy array and reverse its elements.

In [81]:
A=np.array([1,2,4,5,6,7,8])
A[::-1]

array([8, 7, 6, 5, 4, 2, 1])

Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [20]:
x = np.array([[1,2,3]
              ,[4,5,6],
              [7,8,9]])
y=np.array([[10,11,12]
              ,[13,14,15],
              [16,17,19]])
x*y

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 171]])

Exercise 18:
Create a diagonal matrix from a given 1D array.

In [92]:
A = np.array([1, 2, 3, 4])  
np.diag(A) 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [19]:
x = np.array([[1,2]
              ,[3,4]])
y=np.array([[5,6]
              ,[7,8]])
np.dot(x,y)

array([[19, 22],
       [43, 50]])

Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [103]:
x = np.array([[1,2]
              ,[3,4]])
x.flatten()

array([1, 2, 3, 4])

Exercise 21:
Stack two NumPy arrays vertically.

In [118]:
x = np.array([[1,2]
              ,[3,4]])
y=np.array([[5,6]
              ,[7,8]])
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Exercise 22:
Stack two NumPy arrays horizontally.

In [119]:
x = np.array([[1,2]
              ,[3,4]])
y=np.array([[5,6]
              ,[7,8]])
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [18]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])  
A_subs = np.split(A, 3)  
A_subs

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [17]:
A = np.random.rand(3, 4)  
rounded_A = np.round(A, 2)  
rounded_A

array([[0.  , 0.08, 0.18, 0.14],
       [0.41, 0.96, 0.74, 0.66],
       [0.17, 0.59, 0.44, 0.12]])

Exercise 25:
Find the unique elements of a NumPy array

In [16]:
A = np.array([1, 2, 2, 3, 4, 4, 5, 6, 1])   
unique_A = np.unique(A)  
unique_A

array([1, 2, 3, 4, 5, 6])

Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [15]:
A = np.array([1, 5, 3, 7, 2, 8, 0, 4])  
my_value = 3   
A[A < my_value] = my_value
A

array([3, 5, 3, 7, 3, 8, 3, 4])

Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [14]:
A = np.array([1, 2, 3, 4, 5])  
A_cumulative_sum = np.cumsum(A)  
A_cumulative_sum

array([ 1,  3,  6, 10, 15])

Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [13]:
A = np.array([1, 0, 3, 4, 0, 5, 0, 7, 0])  
non_zero_element = np.count_nonzero(A)  
non_zero_element

5

Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [12]:
A = np.random.randint(0, 100, size=10) 
sorted_A = np.sort(A)  
sorted_A

array([ 3,  6, 17, 21, 47, 48, 57, 72, 79, 89])

Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [26]:
A = np.array([[1, 2, 3],  
              [4, 5, 6],  
              [7, 8, 9]])   
row_wise_sum = np.sum(A, axis=1)   
column_wise_sum = np.sum(A, axis=0)  
print("\nRow-wise Sum:")  
print(row_wise_sum)  

print("\nColumn-wise Sum:")  
print(column_wise_sum)


Row-wise Sum:
[ 6 15 24]

Column-wise Sum:
[12 15 18]


Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [30]:
A = np.random.rand(5, 5) * 100  
min_value = np.min(A)  
max_value = np.max(A)  
normalized_array = (A - min_value) / (max_value - min_value)   
print("\nNormalized Array:")  
normalized_array


Normalized Array:


array([[0.56196831, 0.54651302, 0.48243909, 1.        , 0.8418586 ],
       [0.11888224, 0.25154797, 0.90505447, 0.23504893, 0.35557122],
       [0.12315184, 0.16182845, 0.34891927, 0.4445257 , 0.64785566],
       [0.36081541, 0.42568221, 0.7729847 , 0.        , 0.99991415],
       [0.83258919, 0.9050272 , 0.46814711, 0.39546932, 0.97347375]])

Exercise 32:
Create two NumPy arrays and find the dot product.

In [33]:
A = np.array([1, 2, 3])  
B = np.array([4, 5, 6])   
dot_AB = np.dot(A, B)   
print("The dot product is : ",dot_AB)

The dot product is :  32


Exercise 33:
Find the trace of a square NumPy matrix.

In [34]:
A = np.array([[1, 2, 3],  
                   [4, 5, 6],  
                   [7, 8, 9]])  

trace_A = np.trace(A)  
trace_A

15

Exercise 34:
Create a 2D array and swap two rows.

In [63]:
import numpy as np

# Create a 2D NumPy array
A = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print("Before swap:") 
print(A)
A[[0, 2]] = A[[2, 0]]

print("\nMatrix After Swapping Row 0 and Row 2:")
print(A)



Before swap:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix After Swapping Row 0 and Row 2:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [38]:
A = np.array([1, 2, 3, 4, 5])
col_A = A.reshape(-1, 1)
print("\nColumn Vector:")
col_A



Column Vector:


array([[1],
       [2],
       [3],
       [4],
       [5]])

Exercise 36:
Find the determinant of a 3x3 matrix.

In [50]:
A = np.array([[1, 0, 5],
                   [0, 1, 8],
                   [0, 0, 1]])
det_A = np.linalg.det(A)
print(f"Determinant of A is : {det_A}")


Determinant of A is : 1.0


Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [51]:
A = np.array([[4, 2],
                   [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


Exercise 38:
Solve a system of linear equations using NumPy.

In [52]:
A = np.array([[2, 1], 
              [1, 3]])

# Constants
B = np.array([5, 9])
solved = np.linalg.solve(A, B)
print("(x, y):", solved)


(x, y): [1.2 2.6]


Exercise 39:
Add Gaussian noise to a NumPy array.

In [56]:
A = np.array([1, 2, 3, 4, 5])
mean = 0
std_dev = 0.1
noise = np.random.normal(mean, std_dev, A.shape)
noisy = A + noise
print(A)
print("=================================================================")
noisy


[1 2 3 4 5]


array([1.04373909, 1.88365062, 3.04441355, 3.86381739, 4.96101287])

Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [57]:
A = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
diagonal_A = np.diag(A)
diagonal_A


array([ 1,  6, 11, 16])

Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

In [59]:
A = np.random.rand(100) * 100
clipped_A = np.clip(A, 10, 50)
clipped_A


array([50.        , 40.16474172, 50.        , 35.68402134, 50.        ,
       20.13291321, 18.80730271, 14.27659548, 50.        , 50.        ,
       12.00650365, 13.85496226, 12.88066338, 50.        , 50.        ,
       50.        , 10.        , 33.95592457, 10.        , 50.        ,
       50.        , 35.39928349, 16.42511882, 24.47197683, 50.        ,
       32.15447654, 13.12917283, 50.        , 50.        , 33.56909396,
       10.        , 25.88706247, 14.07668786, 50.        , 20.77285028,
       14.52617725, 44.09455589, 38.54795453, 18.08318358, 23.471765  ,
       26.44114841, 45.6303942 , 50.        , 50.        , 24.22900004,
       50.        , 50.        , 50.        , 34.37490996, 50.        ,
       50.        , 42.86443618, 42.52641337, 50.        , 10.        ,
       50.        , 10.        , 10.        , 45.15795884, 20.90413687,
       10.        , 11.48594434, 50.        , 50.        , 10.        ,
       50.        , 50.        , 40.86488679, 50.        , 12.96

Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

In [61]:
A = np.array([[4, -2, 7], 
              [-5, 3, -8], 
              [6, -1, 9]])
A[A < 0] = 0
A


array([[4, 0, 7],
       [0, 3, 0],
       [6, 0, 9]])

Exercise 43:
Find the inner and outer products of two NumPy arrays.

In [65]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
inner_product = np.inner(array_a, array_b)
outer_product = np.outer(array_a, array_b)
print("Inner Product:", inner_product)
print("Outer Product:\n", outer_product)


Inner Product: 32
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

In [73]:
points = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
pairwise_distances = pdist(points)
distance_matrix = squareform(pairwise_distances)
print("Pairwise Distances:\n", distance_matrix)


Pairwise Distances:
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


Exercise 45:
Create a structured NumPy array with fields for name, age, and height.

In [79]:
A = np.dtype([
    ('name', 'U20'),   
    ('age', 'i4'),     
    ('height', 'f4')   
])
structured_A = np.array([
    ('Alice', 25, 5.5),
    ('Bob', 30, 6.0),
    ('Charlie', 22, 5.8)
], dtype=A)
print(structured_A)


[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 22, 5.8)]


Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

In [80]:
A = np.random.randint(0, 10, size=(5, 5))
print(A)
unique, counts = np.unique(matrix, return_counts=True)
occurrences = dict(zip(unique, counts))
print("\nOccurrences of each unique value:")
for value, count in occurrences.items():
    print(f"Value {value}: {count} times")


[[2 9 2 1 3]
 [1 5 5 5 6]
 [3 6 1 6 5]
 [3 9 6 2 3]
 [6 0 4 9 8]]

Occurrences of each unique value:
Value 1: 1 times
Value 2: 1 times
Value 3: 1 times
Value 4: 1 times
Value 5: 1 times
Value 6: 1 times
Value 7: 1 times
Value 8: 1 times
Value 9: 1 times


Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

In [81]:
A = np.random.rand(3, 3)
print("Before Subtracting Row")
print(A)
subtracted_A = A - A.mean(axis=1, keepdims=True)
print("\nArray After Subtracting Row Means:")
print(subtracted_A)


Before Subtracting Row
[[0.64721017 0.48075374 0.57259226]
 [0.84307969 0.41962686 0.85247131]
 [0.76811856 0.46515235 0.22870865]]

Array After Subtracting Row Means:
[[ 0.08035812 -0.08609832  0.0057402 ]
 [ 0.1380204  -0.28543242  0.14741202]
 [ 0.28079204 -0.02217417 -0.25861787]]


Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

In [83]:
A = np.random.randint(0, 100, size=(10,))
print("Random Array:")
print(A)
any_greater_than_50 = np.any(A > 50)
print("\nAny value greater than 50:", any_greater_than_50)


Random Array:
[74 69 59 50 43 97 90 44 68 81]

Any value greater than 50: True


Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

In [85]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([2, 4, 6, 8, 10])
correlation_AB = np.corrcoef(A, B)
pearson_correlation = correlation_AB[0, 1]
print("Pearson Correlation Coefficient:", pearson_correlation)


Pearson Correlation Coefficient: 0.9999999999999999
