Practical_6: Numpy

Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [2]:
import numpy as np

In [12]:
my_int=np.arange(1,11)
my_int

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [13]:
my_array = np.array([[0,0,0], [0,0,0], [0,0,0]])
my_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [14]:
my_evenly = np.linspace(0, 5, 10)
print(my_evenly)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [24]:
my_five = np.array([[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0],[0,0,0,1,0], [0,0,0,0,1]])
my_five

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [19]:
matrix = np.random.rand(4, 4)  
matrix

array([[0.93711163, 0.15623631, 0.84303857, 0.15524518],
       [0.77326055, 0.01054402, 0.64864639, 0.37636548],
       [0.40858546, 0.31339509, 0.18992873, 0.56441552],
       [0.49713107, 0.39625419, 0.08598607, 0.36775246]])

Exercise 6:
Find the shape of a NumPy array.

In [20]:
print("matrix shape:", matrix.shape)

matrix shape: (4, 4)


Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [35]:
array_1d = np.arange(16)  
matrix_4 = array_1d.reshape(4, 4)  
my_A=array_1d
my_A
matrix_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
np.random.seed(10)
A=np.random.rand(4,4)
A

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [30]:
np.random.seed(10)
A=np.random.rand(4,4)
A


array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

Exercise 8:
Find the data type of the elements in a NumPy array.

In [36]:
A.dtype

dtype('float64')

Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [44]:
A=np.arange(2,101,2)
A

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [48]:
A=np.random.randint(10,50,(6,6))
A

array([[22, 15, 49, 18, 47, 47],
       [19, 46, 16, 31, 11, 16],
       [12, 43, 46, 39, 34, 28],
       [46, 12, 19, 45, 27, 46],
       [38, 29, 12, 10, 41, 13],
       [20, 45, 17, 18, 38, 47]])

Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [56]:
import numpy as np  
A = np.array([[1, 2, 3, 4],  
              [5, 6, 7, 8],  
              [9, 10, 11, 12],  
              [13, 14, 15, 16]])   
submatrix = A[1:3, 1:3] 
print(A)  

print("\nExtracted Submatrix:")  
print(submatrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Extracted Submatrix:
[[ 6  7]
 [10 11]]


Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [57]:
A=np.array([1,2,3,4,5])
np.sum(A)

15

Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [58]:
A=np.array([1,2,3,4,5])
np.mean(A)

3.0

In [64]:
A=np.array([5,3,1,4,2])
B=np.sort(A)
C=len(B)
if(C%2==0):
    print("Median is ", C/2)
else:
    print("Median is ",(C+1)/2)

Median is  3.0


In [69]:
A=np.array([5,3,1,4,2])
np.std(A,ddof=0)

1.4142135623730951

In [66]:
help(np.std)

Help on _ArrayFunctionDispatcher in module numpy:

std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
    Compute the standard deviation along the specified axis.

    Returns the standard deviation, a measure of the spread of a distribution,
    of the array elements. The standard deviation is computed for the
    flattened array by default, otherwise over the specified axis.

    Parameters
    ----------
    a : array_like
        Calculate the standard deviation of these values.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the standard deviation is computed. The
        default is to compute the standard deviation of the flattened array.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a standard deviation is performed over
        multiple axes, instead of a single axis or all the axes as before.
    dtype : dtype, optional
        Type to use in computing the standard deviation. For 

Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [71]:
A=np.array([5,3,1,4,2])
print("The maximum is : ",np.max(A))
print("The minimum is : ",np.min(A))

The maximum is :  5
The minimum is :  1


Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [22]:
A = np.random.randint(0, 100, size=20)  
print(A)
maxvalue=np.argmax(A)
print(maxvalue)

[99 82 14 75 54 51 16 15 19 32 17 76 53  7  9 23 14 11 92 62]
0


Exercise 16:
Create a NumPy array and reverse its elements.

In [81]:
A=np.array([1,2,4,5,6,7,8])
A[::-1]

array([8, 7, 6, 5, 4, 2, 1])

Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [20]:
x = np.array([[1,2,3]
              ,[4,5,6],
              [7,8,9]])
y=np.array([[10,11,12]
              ,[13,14,15],
              [16,17,19]])
x*y

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 171]])

Exercise 18:
Create a diagonal matrix from a given 1D array.

In [92]:
A = np.array([1, 2, 3, 4])  
np.diag(A) 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [19]:
x = np.array([[1,2]
              ,[3,4]])
y=np.array([[5,6]
              ,[7,8]])
np.dot(x,y)

array([[19, 22],
       [43, 50]])

Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [103]:
x = np.array([[1,2]
              ,[3,4]])
x.flatten()

array([1, 2, 3, 4])

Exercise 21:
Stack two NumPy arrays vertically.

In [118]:
x = np.array([[1,2]
              ,[3,4]])
y=np.array([[5,6]
              ,[7,8]])
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Exercise 22:
Stack two NumPy arrays horizontally.

In [119]:
x = np.array([[1,2]
              ,[3,4]])
y=np.array([[5,6]
              ,[7,8]])
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [18]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])  
A_subs = np.split(A, 3)  
A_subs

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [17]:
A = np.random.rand(3, 4)  
rounded_A = np.round(A, 2)  
rounded_A

array([[0.  , 0.08, 0.18, 0.14],
       [0.41, 0.96, 0.74, 0.66],
       [0.17, 0.59, 0.44, 0.12]])

Exercise 25:
Find the unique elements of a NumPy array

In [16]:
A = np.array([1, 2, 2, 3, 4, 4, 5, 6, 1])   
unique_A = np.unique(A)  
unique_A

array([1, 2, 3, 4, 5, 6])

Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [15]:
A = np.array([1, 5, 3, 7, 2, 8, 0, 4])  
my_value = 3   
A[A < my_value] = my_value
A

array([3, 5, 3, 7, 3, 8, 3, 4])

Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [14]:
A = np.array([1, 2, 3, 4, 5])  
A_cumulative_sum = np.cumsum(A)  
A_cumulative_sum

array([ 1,  3,  6, 10, 15])

Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [13]:
A = np.array([1, 0, 3, 4, 0, 5, 0, 7, 0])  
non_zero_element = np.count_nonzero(A)  
non_zero_element

5

Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [12]:
A = np.random.randint(0, 100, size=10) 
sorted_A = np.sort(A)  
sorted_A

array([ 3,  6, 17, 21, 47, 48, 57, 72, 79, 89])

Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [ ]:
matrix = np.array([[1, 2, 3],  
                   [4, 5, 6],  
                   [7, 8, 9]]) 
row-wise_sum = np.sum(matrix, axis=1)  
column-wise_sum = np.sum(matrix, axis=0)
print("\nRow-wise Sum:")  
print(row-wise_sum)  

print("\nColumn-wise Sum:")  
print(column-wise_sum)